// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVYkC1w9jxOEDHIBJ6b2LhrUqjfI7I09Y',
    appId: '1:270760836618:web:0bf2ed55c755c09e3f29f3',
    messagingSenderId: '270760836618',
    projectId: 'kira-ai-7ffe5',
    authDomain: 'kira-ai-7ffe5.firebaseapp.com',
    storageBucket: 'kira-ai-7ffe5.firebasestorage.app',
    measurementId: 'G-X3NTV2TZTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWZBdt1ucJtY2OxxqWExe5tQwcXUdOZ4',
    appId: '1:270760836618:android:e8a84a4230776f843f29f3',
    messagingSenderId: '270760836618',
    projectId: 'kira-ai-7ffe5',
    storageBucket: 'kira-ai-7ffe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSt0Re0_B_xgQpWbWj_0cfSFqcTri8xc',
    appId: '1:270760836618:ios:7b352872e8fe73ec3f29f3',
    messagingSenderId: '270760836618',
    projectId: 'kira-ai-7ffe5',
    storageBucket: 'kira-ai-7ffe5.firebasestorage.app',
    androidClientId: '270760836618-ecst64ndha1t6tgfnukqoksm0k449ild.apps.googleusercontent.com',
    iosClientId: '270760836618-h1brp93q1h42pr8j5tkdrguc1v93n8ns.apps.googleusercontent.com',
    iosBundleId: 'com.bhumiqai.voiceChatbotAssistant',
  );

}